/*
 * generated by Xtext 2.14.0
 */
package org.xtext.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor
import com.google.inject.Module

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class MQLUiModule extends AbstractMQLUiModule implements Module {
}
