/*
 * generated by Xtext 2.14.0
 */
package org.xtext

import com.google.inject.Injector
import org.eclipse.emf.ecore.EPackage
import qmm.QmmPackage

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MQLStandaloneSetup extends MQLStandaloneSetupGenerated {
	def static void doSetup() {
		new MQLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
