/*
 * generated by Xtext 2.14.0
 */
package org.xtext.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.services.MQLGrammarAccess;

@SuppressWarnings("all")
public class MQLSyntacticSequencer extends AbstractSyntacticSequencer {

	protected MQLGrammarAccess grammarAccess;
	protected AbstractElementAlias match_AdditionalInformation_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_AttributeFamily_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_AttributeLib_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_AttributeNameMapping_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_AttributeValueRequirement_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_Attribute_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_CAEXBasicObject_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_CAEXFile_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_CAEXObject_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_Copyright_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_Description_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_DocumentRoot_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3__q;
	protected AbstractElementAlias match_Element_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_ExternalInterface_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_ExternalReferenceType_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_GenericAttribute_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_GenericElement_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_InstanceHierarchy_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_InterfaceClassLib_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_InterfaceClass_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_InterfaceFamily_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_InterfaceIDMapping_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_InternalElement_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_InternalLink_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_Mapping_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_NominalScaledType_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3__q;
	protected AbstractElementAlias match_OrdinalScaledType_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_RefSemantic_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_Revision_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_RoleClassLib_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_RoleClass_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_RoleFamily_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_RoleRequirements_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_SourceDocumentInformation_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_SupportedRoleClass_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_SystemUnitClassLib_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_SystemUnitClass_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_SystemUnitFamily_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_UnknownType_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	protected AbstractElementAlias match_Version_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (MQLGrammarAccess) access;
		match_AdditionalInformation_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getAdditionalInformation_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getAdditionalInformation_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_AttributeFamily_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getAttributeFamily_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getAttributeFamily_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_AttributeLib_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getAttributeLib_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getAttributeLib_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_AttributeNameMapping_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getAttributeNameMapping_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getAttributeNameMapping_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_AttributeValueRequirement_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getAttributeValueRequirement_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getAttributeValueRequirement_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_Attribute_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getAttribute_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getAttribute_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_CAEXBasicObject_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getCAEXBasicObject_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getCAEXBasicObject_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_CAEXFile_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getCAEXFile_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getCAEXFile_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_CAEXObject_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getCAEXObject_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getCAEXObject_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_Copyright_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getCopyright_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getCopyright_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_Description_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getDescription_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getDescription_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_DocumentRoot_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getDocumentRoot_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getDocumentRoot_bodyAccess().getRightCurlyBracketKeyword_3()));
		match_Element_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getElement_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getElement_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_ExternalInterface_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getExternalInterface_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getExternalInterface_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_ExternalReferenceType_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getExternalReferenceType_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getExternalReferenceType_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_GenericAttribute_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getGenericAttribute_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getGenericAttribute_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_GenericElement_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getGenericElement_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getGenericElement_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_InstanceHierarchy_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getInstanceHierarchy_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getInstanceHierarchy_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_InterfaceClassLib_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getInterfaceClassLib_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getInterfaceClassLib_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_InterfaceClass_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getInterfaceClass_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getInterfaceClass_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_InterfaceFamily_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getInterfaceFamily_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getInterfaceFamily_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_InterfaceIDMapping_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getInterfaceIDMapping_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getInterfaceIDMapping_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_InternalElement_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getInternalElement_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getInternalElement_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_InternalLink_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getInternalLink_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getInternalLink_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_Mapping_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getMapping_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getMapping_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_NominalScaledType_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getNominalScaledType_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getNominalScaledType_bodyAccess().getRightCurlyBracketKeyword_3()));
		match_OrdinalScaledType_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getOrdinalScaledType_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getOrdinalScaledType_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_RefSemantic_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getRefSemantic_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getRefSemantic_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_Revision_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getRevision_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getRevision_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_RoleClassLib_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getRoleClassLib_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getRoleClassLib_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_RoleClass_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getRoleClass_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getRoleClass_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_RoleFamily_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getRoleFamily_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getRoleFamily_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_RoleRequirements_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getRoleRequirements_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getRoleRequirements_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_SourceDocumentInformation_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getSourceDocumentInformation_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getSourceDocumentInformation_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_SupportedRoleClass_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getSupportedRoleClass_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getSupportedRoleClass_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_SystemUnitClassLib_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getSystemUnitClassLib_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getSystemUnitClassLib_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_SystemUnitClass_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getSystemUnitClass_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getSystemUnitClass_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_SystemUnitFamily_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getSystemUnitFamily_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getSystemUnitFamily_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_UnknownType_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getUnknownType_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getUnknownType_bodyAccess().getRightCurlyBracketKeyword_4()));
		match_Version_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getVersion_bodyAccess().getLeftCurlyBracketKeyword_1()), new TokenAlias(false, false, grammarAccess.getVersion_bodyAccess().getRightCurlyBracketKeyword_4()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_AdditionalInformation_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_AdditionalInformation_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_AttributeFamily_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_AttributeFamily_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_AttributeLib_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_AttributeLib_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_AttributeNameMapping_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_AttributeNameMapping_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_AttributeValueRequirement_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_AttributeValueRequirement_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Attribute_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_Attribute_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_CAEXBasicObject_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_CAEXBasicObject_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_CAEXFile_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_CAEXFile_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_CAEXObject_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_CAEXObject_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Copyright_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_Copyright_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Description_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_Description_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_DocumentRoot_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3__q.equals(syntax))
				emit_DocumentRoot_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Element_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_Element_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ExternalInterface_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_ExternalInterface_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_ExternalReferenceType_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_ExternalReferenceType_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_GenericAttribute_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_GenericAttribute_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_GenericElement_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_GenericElement_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_InstanceHierarchy_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_InstanceHierarchy_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_InterfaceClassLib_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_InterfaceClassLib_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_InterfaceClass_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_InterfaceClass_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_InterfaceFamily_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_InterfaceFamily_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_InterfaceIDMapping_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_InterfaceIDMapping_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_InternalElement_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_InternalElement_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_InternalLink_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_InternalLink_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Mapping_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_Mapping_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_NominalScaledType_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3__q.equals(syntax))
				emit_NominalScaledType_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_OrdinalScaledType_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_OrdinalScaledType_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_RefSemantic_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_RefSemantic_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Revision_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_Revision_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_RoleClassLib_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_RoleClassLib_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_RoleClass_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_RoleClass_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_RoleFamily_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_RoleFamily_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_RoleRequirements_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_RoleRequirements_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_SourceDocumentInformation_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_SourceDocumentInformation_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_SupportedRoleClass_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_SupportedRoleClass_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_SystemUnitClassLib_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_SystemUnitClassLib_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_SystemUnitClass_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_SystemUnitClass_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_SystemUnitFamily_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_SystemUnitFamily_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_UnknownType_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_UnknownType_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Version_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q.equals(syntax))
				emit_Version_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'AdditionalInformation' (ambiguity) (rule start)
	 */
	protected void emit_AdditionalInformation_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'AttributeFamily' (ambiguity) (rule start)
	 */
	protected void emit_AttributeFamily_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'AttributeLib' (ambiguity) (rule start)
	 */
	protected void emit_AttributeLib_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'AttributeNameMapping' (ambiguity) (rule start)
	 */
	protected void emit_AttributeNameMapping_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'AttributeValueRequirement' (ambiguity) (rule start)
	 */
	protected void emit_AttributeValueRequirement_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'Attribute' (ambiguity) (rule start)
	 */
	protected void emit_Attribute_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'CAEXBasicObject' (ambiguity) (rule start)
	 */
	protected void emit_CAEXBasicObject_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'CAEXFile' (ambiguity) (rule start)
	 */
	protected void emit_CAEXFile_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'CAEXObject' (ambiguity) (rule start)
	 */
	protected void emit_CAEXObject_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'Copyright' (ambiguity) (rule start)
	 */
	protected void emit_Copyright_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'Description' (ambiguity) (rule start)
	 */
	protected void emit_Description_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'DocumentRoot' (ambiguity) (rule start)
	 */
	protected void emit_DocumentRoot_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'Element' (ambiguity) (rule start)
	 */
	protected void emit_Element_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'ExternalInterface' (ambiguity) (rule start)
	 */
	protected void emit_ExternalInterface_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'ExternalReferenceType' (ambiguity) (rule start)
	 */
	protected void emit_ExternalReferenceType_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'GenericAttribute' (ambiguity) (rule start)
	 */
	protected void emit_GenericAttribute_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'GenericElement' (ambiguity) (rule start)
	 */
	protected void emit_GenericElement_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'InstanceHierarchy' (ambiguity) (rule start)
	 */
	protected void emit_InstanceHierarchy_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'InterfaceClassLib' (ambiguity) (rule start)
	 */
	protected void emit_InterfaceClassLib_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'InterfaceClass' (ambiguity) (rule start)
	 */
	protected void emit_InterfaceClass_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'InterfaceFamily' (ambiguity) (rule start)
	 */
	protected void emit_InterfaceFamily_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'InterfaceIDMapping' (ambiguity) (rule start)
	 */
	protected void emit_InterfaceIDMapping_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'InternalElement' (ambiguity) (rule start)
	 */
	protected void emit_InternalElement_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'InternalLink' (ambiguity) (rule start)
	 */
	protected void emit_InternalLink_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'Mapping' (ambiguity) (rule start)
	 */
	protected void emit_Mapping_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'NominalScaledType' (ambiguity) (rule start)
	 */
	protected void emit_NominalScaledType_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'OrdinalScaledType' (ambiguity) (rule start)
	 */
	protected void emit_OrdinalScaledType_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'RefSemantic' (ambiguity) (rule start)
	 */
	protected void emit_RefSemantic_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'Revision' (ambiguity) (rule start)
	 */
	protected void emit_Revision_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'RoleClassLib' (ambiguity) (rule start)
	 */
	protected void emit_RoleClassLib_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'RoleClass' (ambiguity) (rule start)
	 */
	protected void emit_RoleClass_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'RoleFamily' (ambiguity) (rule start)
	 */
	protected void emit_RoleFamily_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'RoleRequirements' (ambiguity) (rule start)
	 */
	protected void emit_RoleRequirements_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'SourceDocumentInformation' (ambiguity) (rule start)
	 */
	protected void emit_SourceDocumentInformation_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'SupportedRoleClass' (ambiguity) (rule start)
	 */
	protected void emit_SupportedRoleClass_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'SystemUnitClassLib' (ambiguity) (rule start)
	 */
	protected void emit_SystemUnitClassLib_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'SystemUnitClass' (ambiguity) (rule start)
	 */
	protected void emit_SystemUnitClass_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'SystemUnitFamily' (ambiguity) (rule start)
	 */
	protected void emit_SystemUnitFamily_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'UnknownType' (ambiguity) (rule start)
	 */
	protected void emit_UnknownType_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'Version' (ambiguity) (rule start)
	 */
	protected void emit_Version_body___LeftCurlyBracketKeyword_1_RightCurlyBracketKeyword_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
