package org.xtext.ui.util;
import org.eclipse.core.resources.ResourcesPlugin;

/**This class was automatically generated by the MQLSetup**/
public class Constants{
		/* WORKSPACE CONSTANT */
		public final static String WORKSPACE_PATH = (ResourcesPlugin.getWorkspace().getRoot().getLocation().toFile().toString()).replace("\\", "/") + "/../../org.xtext.MQL.ui";

		/* DMM CONSTANTS */
		public final static String DMM_NsPrefix="caex";
		public final static String DMM_NAME = "DMM";
		public final static String DMM_NsURI = "/MQLSetup/model/" + DMM_NAME + ".ecore";
		public final static String DMM_PATH = (ResourcesPlugin.getWorkspace().getRoot().getLocation().toFile().toString()).replace("\\", "/") + "/../.." + DMM_NsURI;

		/* QMM CONSTANTS */
		public final static String QMM_NAME = "QMM";
		public final static String QMM_NsURI = "/" + QMM_NAME + "/model/" + QMM_NAME + ".ecore";

		/* QRMM CONSTANTS */
		public final static String QRMM_NAME = "QRMM";
		public final static String QRMM_NsURI = "/" + QRMM_NAME + "/model/" + QRMM_NAME + ".ecore";

		/* ATL CONSTANTS */
		public final static String ATL_TRANSFORMATION_DIR_PATH = WORKSPACE_PATH + "/transformation/";
		public final static String ATL_TRANSFORMATION_MODULE_NAME = DMM_NAME + "2" + QRMM_NAME;
		public final static String TRANSFORMED_DOMAINMODEL_PATH = ATL_TRANSFORMATION_DIR_PATH + "transformedDomainModel.xmi";

		/* VQL CONSTANT */
		public final static String VQL_QUERY_PATH = WORKSPACE_PATH + "/runtime/MQLRuntime/src-gen/Query.vql";
}