/*
 * generated by Xtext 2.14.0
 */
package org.xtext.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.MQLRuntimeModule
import org.xtext.MQLStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MQLIdeSetup extends MQLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MQLRuntimeModule, new MQLIdeModule))
	}
	
}
