/*
 * generated by Xtext 2.14.0
 */
package org.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.parser.antlr.internal.InternalMQLParser;
import org.xtext.services.MQLGrammarAccess;

public class MQLParser extends AbstractAntlrParser {

	@Inject
	private MQLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMQLParser createParser(XtextTokenStream stream) {
		return new InternalMQLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Query";
	}

	public MQLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MQLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
