/**
 * generated by Xtext 2.14.0
 */
package org.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.MQLRuntimeModule;
import org.xtext.MQLStandaloneSetup;
import org.xtext.ide.MQLIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MQLIdeSetup extends MQLStandaloneSetup {
  @Override
  public Injector createInjector() {
    MQLRuntimeModule _mQLRuntimeModule = new MQLRuntimeModule();
    MQLIdeModule _mQLIdeModule = new MQLIdeModule();
    return Guice.createInjector(Modules2.mixin(_mQLRuntimeModule, _mQLIdeModule));
  }
}
