/**
 * generated by Xtext 2.14.0
 */
package org.xtext.ide;

import org.xtext.ide.AbstractMQLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MQLIdeModule extends AbstractMQLIdeModule {
}
