/**
 * generated by Xtext 2.14.0
 */
package org.xtext;

import org.eclipse.xtext.scoping.IScopeProvider;
import org.xtext.AbstractMQLRuntimeModule;
import org.xtext.scoping.MQLScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MQLRuntimeModule extends AbstractMQLRuntimeModule {
  @Override
  public Class<? extends IScopeProvider> bindIScopeProvider() {
    return MQLScopeProvider.class;
  }
}
